export const SLOVAK_CITIES: string[] = [
  "Bánovce nad Bebravou",
  "Banská Bystrica",
  "Banská Štiavnica",
  "Bardejov",
  "Bratislava",
  "Brezno",
  "Brezová pod Bradlom",
  "Bytča",
  "Čadca",
  "Detva",
  "Dobšiná",
  "Dolný Kubín",
  "Dudince",
  "Dunajská Streda",
  "Fiľakovo",
  "Gabčíkovo",
  "Galanta",
  "Gbely",
  "Gelnica",
  "Giraltovce",
  "Handlová",
  "Hanušovce nad Topľou",
  "Hlohovec",
  "Hnúšťa",
  "Holíč",
  "Humenné",
  "Hurbanovo",
  "Ilava",
  "Jelšava",
  "Kežmarok",
  "Kolárovo",
  "Komárno",
  "Košice",
  "Kremnica",
  "Krupina",
  "Kysucké Nové Mesto",
  "Leopoldov",
  "Levice",
  "Lipany",
  "Liptovský Hrádok",
  "Liptovský Mikuláš",
  "Lučenec",
  "Malacky",
  "Martin",
  "Medzev",
  "Medzilaborce",
  "Michalovce",
  "Modra",
  "Modrý Kameň",
  "Moldava nad Bodvou",
  "Myjava",
  "Námestovo",
  "Nitra",
  "Nová Baňa",
  "Nová Dubnica",
  "Nové Mesto nad Váhom",
  "Nové Zámky",
  "Partizánske",
  "Pezinok",
  "Piešťany",
  "Podolínec",
  "Považská Bystrica",
  "Prešov",
  "Prievidza",
  "Púchov",
  "Rajec",
  "Revúca",
  "Rimavská Sobota",
  "Rožňava",
  "Ružomberok",
  "Sabinov",
  "Šahy",
  "Šaľa",
  "Šamorín",
  "Sečovce",
  "Senec",
  "Senica",
  "Sereď",
  "Skalica",
  "Sládkovičovo",
  "Snina",
  "Sobrance",
  "Spišská Belá",
  "Spišská Nová Ves",
  "Spišská Stará Ves",
  "Spišské Podhradie",
  "Spišské Vlachy",
  "Stará Ľubovňa",
  "Stará Turá",
  "Stropkov",
  "Štúrovo",
  "Stupava",
  "Svidník",
  "Svit",
  "Šurany",
  "Tlmače",
  "Tornaľa",
  "Topoľčany",
  "Trebišov",
  "Trenčianske Teplice",
  "Trenčín",
  "Trnava",
  "Turčianske Teplice",
  "Turzovka",
  "Tvrdošín",
  "Veľké Kapušany",
  "Veľký Krtíš",
  "Veľký Meder",
  "Veľký Šariš",
  "Vráble",
  "Vranov nad Topľou",
  "Vrútky",
  "Vysoké Tatry",
  "Žarnovica",
  "Žiar nad Hronom",
  "Žilina",
  "Zlaté Moravce",
  "Zvolen",
  "Želiezovce",
];
